language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

notifications:
    email:
      - github@cosinus.org

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod 0755 ./gradlew

script:
  - ./gradlew assembleDebug

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
after_success: ./gradlew coveralls
